version: "3"

services:
  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx/dev/conf.d:/etc/nginx/conf.d
      - ./api/public:/var/www/public
    depends_on:
      - server
      - client
    
  database:
    image: mysql:8.1
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
      ]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./etc/mysql/conf.d:/etc/mysql/conf.d
      - ./etc/mysql/data:/var/lib/mysql

  server:
    build:
      context: ./api
      target: dev
    volumes:
      - ./api:/app
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - PASSWORD=${PASSWORD}
      - HASH_COST=${HASH_COST}
      - ENV=${ENV}
      - ISS=${ISS}
      - JWT_SECRET=${JWT_SECRET}
      - ACCESS_CONTROL_ALLOW_ORIGIN=${ACCESS_CONTROL_ALLOW_ORIGIN}
    depends_on:
      database:
        condition: service_healthy

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    depends_on:
      - server  

volumes:
  data:
