import { vars } from '@/styles/theme.css';
import { style } from '@vanilla-extract/css';

export const hamburgerStyle = {
    link: style({
        position: 'fixed',
        top: vars.spacing.relative[5],
        right: vars.spacing.relative[16],
        zIndex: vars.zIndex.windowFloat,
    }),
    hamburger: style({
        position: 'fixed',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: vars.spacing.relative[5],
        top: vars.spacing.relative[10],
        right: vars.spacing.relative[5],
        zIndex: vars.zIndex.windowFloat,
        width: '14%',
        minWidth: '12rem',
        height: '54%',
        minHeight: '25rem',
        borderRadius: vars.border.radius[5],
        background: vars.color.gray[50],
        boxShadow: vars.shadow.window,
    }),
    hamburgerButton: style({
        position: 'fixed',
        top: vars.spacing.relative[5],
        right: vars.spacing.relative[5],
        zIndex: vars.zIndex.windowFloat,
    }),
    hamburgerOuter: style({
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: vars.spacing.relative[3],
        borderRadius: vars.border.radius[5],
        background: vars.color.gray[50],
    }),
    hamburgerInner: style({
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: vars.font.size['2xl'],
        listStyle: 'none',
        marginTop: vars.spacing.relative[4],
    }),
    hamburgerSpan: style({
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        background: vars.color.gray[50],
        marginTop: vars.spacing.relative[8],
    }),
    hamburgerAnchor: {
        anchor: style({
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            textDecoration: 'none',
            padding: vars.spacing.relative[2],
            cursor: 'pointer',
            transition: 'all 0.2s ease-in-out',
            borderRadius: vars.border.radius[4],
            marginRight: vars.spacing.relative[2],
            ":hover": {
                opacity: 0.8,
                backgroundColor: vars.color.gray[300],
            },
        }),
        list: style({
            textDecoration: 'none',
            alignItems: 'center',
            justifyContent: 'center',
            paddingTop: vars.spacing.relative[1],
            paddingBottom: vars.spacing.relative[1],
            paddingRight: vars.spacing.relative[4],
            paddingLeft: vars.spacing.relative[4],
            borderRadius: vars.border.radius[5],
            color: vars.color.gray[900],
            cursor: 'pointer',
            transition: 'all 0.2s ease-in-out',
            ":hover": {
                opacity: 0.8,
                backgroundColor: vars.color.gray[300],
            },
        }),
    },
};
